In [1]:
import pandas as pd
import numpy as np

import yfinance as yf

# Industry ETFs

In [2]:
info = pd.DataFrame(columns=['Description'])
info.loc['SPY'] = 'Domestic Equity SPDR S&P500'
#info.loc['XLC'] = 'Communication Services'
info.loc['XLY'] = 'Consumer Staples'
info.loc['XLP'] = 'Consumer Discretionary'
info.loc['XLE'] = 'Energy'
info.loc['XLF'] = 'Finance'
info.loc['XLV'] = 'Health Care'
info.loc['XLI'] = 'Industrial'
info.loc['XLB'] = 'Materials'
#info.loc['XLRE'] = 'Real Estate'
info.loc['XLK'] = 'Technology'
info.loc['XLU'] = 'Utilities'

info.loc['AAPL'] = 'Apple'
info.loc['AMZN'] = 'Amazon'
info.loc['MSFT'] = 'Microsoft'
#info.loc['FB'] = 'Facebook'

info.loc['GS'] = 'Goldman Sachs'
info.loc['JPM'] = 'JP Morgan'

info

                      Description
SPY   Domestic Equity SPDR S&P500
XLY              Consumer Staples
XLP        Consumer Discretionary
XLE                        Energy
XLF                       Finance
XLV                   Health Care
XLI                    Industrial
XLB                     Materials
XLK                    Technology
XLU                     Utilities
AAPL                        Apple
AMZN                       Amazon
MSFT                    Microsoft
GS                  Goldman Sachs
JPM                     JP Morgan

In [3]:
tickers = list(info.index.values)
df = yf.download(tickers, start="1999-12-31", end="2021-06-30")['Adj Close']

[*********************100%***********************]  15 of 15 completed

In [4]:
prices = df.resample('M').last()
rets = prices.pct_change().iloc[1:,:]
rets

,AAPL,AMZN,GS,JPM,MSFT,SPY,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,
2000-01-31,0.009118,-0.151888,-0.025871,0.044493,-0.161671,-0.049787,-0.122281,0.008074,-0.029586,-0.081794,-0.061485,0.008819,-0.017768,-0.025291,-0.124246
2000-02-29,0.104820,0.066796,0.009550,-0.013168,-0.086845,-0.015227,-0.100469,-0.042334,-0.107046,-0.055173,0.105068,-0.117014,-0.121538,-0.065387,-0.055715
2000-03-31,0.184842,-0.027223,0.137838,0.094977,0.188811,0.096915,0.100893,0.124423,0.182624,0.139207,0.083893,0.037593,0.109237,0.089950,0.141516
2000-04-30,-0.086517,-0.176306,-0.112879,-0.168445,-0.343529,-0.035120,-0.033220,-0.014925,0.009659,0.014445,-0.091847,0.053019,0.065459,-0.011717,-0.020822
2000-05-31,-0.322922,-0.124575,-0.211126,0.035529,-0.103047,-0.015723,-0.031557,0.117424,0.022321,-0.004220,-0.103977,0.071329,-0.002194,-0.026804,-0.053980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-28,-0.079712,-0.035328,0.178154,0.143779,0.004118,0.027805,0.041195,0.224568,0.116062,0.068892,0.013651,-0.012326,-0.060981,-0.021038,-0.005308
2021-03-31,0.007340,0.000372,0.027559,0.034382,0.014588,0.045399,0.075904,0.029710,0.058524,0.089869,0.019029,0.084982,0.105521,0.040273,0.044598
2021-04-30,0.076218,0.120663,0.065596,0.016330,0.069602,0.052910,0.053807,0.006726,0.064905,0.035348,0.051879,0.018592,0.041849,0.039318,0.064556
2021-05-31,-0.050497,-0.070470,0.071248,0.067811,-0.007627,0.006566,0.050819,0.057097,0.047711,0.031296,-0.009306,0.017677,-0.023381,0.018709,-0.033982
2021-06-30,0.094053,0.069831,0.001613,-0.061495,0.086991,0.018236,-0.055164,0.029569,-0.034622,-0.030334,0.070022,-0.013120,-0.020227,0.023639,0.033758

In [5]:
with pd.ExcelWriter('industry_equity_data.xlsx') as writer:  
    info.to_excel(writer, sheet_name= 'descriptions')
    rets.to_excel(writer, sheet_name='total returns')
#    retsx.to_excel(writer, sheet_name='excess returns')